title: ChatLab
baseurl: /chatterjee
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md
  - assets/archive
  - assets/img/originals
sass:
  sass_dir: _assets/sass
  style: compressed
keep_files:
  - assets/js
