title: ChatLab
baseurl: /chatterjee
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md
  - assets/archive
  - assets/img/originals
# keep_files:
#   # uncomment to protect gulp output from jekyll clobbering during serve or build
#   - assets/js
#   - assets/css
