title: ChatLab

collections:
  pages:
    # creating collection "pages" inside _pages
    output: true
    permalink: /:path

analytics: false

netlify_login: true

baseurl: null

keep_files: [".git", ".svn"] # default

include: [".htaccess"] # default

exclude:
- netlify.toml
- vendor
- package.json
- package-lock.json
- gulpfile.js
- README.md
- assets/archive
- assets/img/originals

# excluded by default (need to re-exclude because user _config.yml overwrites the default sequence, doesn't append to it)
- Gemfile
- Gemfile.lock
- node_modules
