title: ChatLab
baseurl: /chatterjee
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md
  - assets/archive
  - assets/img/originals
keep_files:
  # things gulp outputs to _site from _assets; these would otherwise get clobbered during jekyll build or serve
  - assets/js
  - assets/css
