backend:
  name: git-gateway
  branch: develop-netlify
publish_mode: editorial_workflow
media_folder: "assets/netlify"
collections:
- name: "pages"
  label: "Pages"
  label_singular: "Page"
  files:
  - name: "research"
    label: "Research Page"
    file: "_data/research.yml"
    fields:
    - name: "publication_list"
      label: "Publications"
      widget: list
      # fields:
  - name: "people"
    label: "People Page"
    file: "_data/people.yml"
    fields:
    - name: "people_list"
      label: "People"
      widget: list
      # fields:
  - name: "news"
    label: "News Page"
    file: "_data/news.yml"
    fields:
    - name: "news_list"
      label: "News Items"
      widget: list
      fields:
      - {name: "title", label: "Article Title", widget: "string", default: ""}
      - {name: "source", label: "Article Source", widget: "string", default: ""}
      - {name: "sub_source", label: "Article Subsource", widget: "string", default: ""}
      - {name: "date", label: "Publish Date", widget: "date", format: "YYYY-MM-DD", default: ""}
      - {name: "media_url", label: "URL", widget: "string", default: ""}
      - name: "media_type"
        label: "Type"
        widget: "select"
        options:
        - {label: "Print", value: "print"}
        - {label: "Audio", value: "audio"}
        - {label: "Video", value: "video"}
