backend:
  name: git-gateway
  branch: develop-netlify
publish_mode: editorial_workflow
media_folder: "assets/netlify"
collections:
- name: "test"
  label: "Folder Collection"
  folder: "_test"
  create: true
  fields:
  - name: "news_list"
    label: "News Items"
    widget: list
    fields:
    - {name: "title", label: "Title", widget: "string"}
    - {name: "test_req_imp", label: "Test Implicit Required", widget: "string"}
    - {name: "test_req_exp", label: "Test Explicit Required", widget: "string", required: true}
    - {name: "test_req_imp_default_str", label: "Test Implicit Required With Default String", widget: "string", default: ""}
    - {name: "test_req_exp_default_str", label: "Test Explicit Required With Default String", widget: "string", required: true, default: ""}
    - {name: "test_req_imp_default_null", label: "Test Implicit Required With Default Null", widget: "string", default: null}
    - {name: "test_req_exp_default_str", label: "Test Explicit Required With Default Null", widget: "string", required: true, default: null}
- name: "pages"
  label: "Pages"
  label_singular: "Page"
  files:
  - name: "research"
    label: "Research Page"
    file: "_data/research.yml"
    fields:
    - name: "publication_list"
      label: "Publications"
      widget: list
      # fields:
  - name: "people"
    label: "People Page"
    file: "_data/people.yml"
    fields:
    - name: "people_list"
      label: "People"
      widget: list
      # fields:
  - name: "news"
    label: "News Page"
    file: "_data/news.json"
    fields:
    - name: "news_list"
      label: "News Items"
      widget: list
      fields:
      - {name: "title", label: "Article Title", widget: "string"}
      - {name: "source", label: "Article Source", widget: "string"}
      - {name: "sub_source", label: "Article Subsource", widget: "string"}
      - {name: "date", label: "Publish Date", widget: "date", format: "YYYY-MM-DD"}
      - {name: "media_url", label: "URL", widget: "string"}
      - name: "media_type"
        label: "Type"
        widget: "select"
        options:
        - {label: "Print", value: "print"}
        - {label: "Audio", value: "audio"}
        - {label: "Video", value: "video"}
